// pack-images.js
const fs = require("fs");
const path = require("path");

const INPUT_DIR = "img";                 // carpeta de imágenes a empaquetar
const OUTPUT_FILE = "assets-images.js";  // archivo generado

function walk(dir) {
  let results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results = results.concat(walk(full));
    else if (/\.(png|webp|jpg|jpeg)$/i.test(entry.name)) results.push(full);
  }
  return results;
}

function mimeFor(file) {
  const ext = path.extname(file).toLowerCase();
  if (ext === ".png") return "image/png";
  if (ext === ".webp") return "image/webp";
  if (ext === ".jpg" || ext === ".jpeg") return "image/jpeg";
  return "application/octet-stream";
}

const files = walk(INPUT_DIR);

const out = [];
out.push("// Auto-generated by pack-images.js. DO NOT EDIT.");
out.push("window.ASSET_IMAGES = window.ASSET_IMAGES || {};");

for (const file of files) {
  const rel = file.replace(/\\/g, "/"); // clave EXACTA con /
  const data = fs.readFileSync(file);
  const b64 = data.toString("base64");
  const mime = mimeFor(file);
  out.push(`window.ASSET_IMAGES[${JSON.stringify(rel)}] = "data:${mime};base64,${b64}";`);
}

fs.writeFileSync(OUTPUT_FILE, out.join("\n"), "utf8");
console.log(`✅ Generated ${OUTPUT_FILE} with ${files.length} images`);
